apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pvc
spec:
  storageClassName: local-storage
  volumeName: kube-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi